title: LASDK Docs
description: Ship what your AI builds, with proof.

defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

exclude:
  - README.md
